package com.rirs.drazba.enumi;



public enum Kategorija {
	AVDIO_VIDEO, AVTO_MOTO, RACUNALNISTVO, OBLACILA, DOM, SPORT, TELEFONIJA, TV_SPREJEMNIK, AKUSTIKA, PRENOSNIKI, TABLICNI_RACUNALNIKI, KOMPONENTE, STACIONARNA_TELEFONIJA, MOBILNA_TELEFONIJA;
}
